config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  # has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    # raise
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    # we need `cocktail_id` to asssociate dose with corresponding cocktail
    @dose.cocktail = @cocktail
    # @dose.save
    # redirect_to cocktail_path(@cocktail)

    if @dose.save
      # raise
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    # raise
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy!
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails List</h1>

<div class="wrapper">
  <div class="container">
    <div class="card">
      <ul class="list">
          <% @cocktails.each do |cocktail| %>
            <li> <%= cocktail.name %>
              <%=  link_to "-> Consult recipe", cocktail_path(cocktail)  %></li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

<%= link_to "+ Add a new Cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<!-- new.html.erb -->
<h1>  Create a new cocktail </h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a Cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<!-- show.html.erb -->




<div class="wrapper">
  <div class="container">

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @cocktail.photo %>');">
        <div class="card-description">
          <div class="card-category">
            <%= @cocktail.name %>
          </div>
          <% @cocktail.doses.each do |dose| %>
            <%= dose.description %> - <%= dose.ingredient.name %>
            <%= link_to dose_path(dose),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
              <i class='fas fa-trash-alt'></i>
            <% end %>
          <% end %>
        </div>
      </div>

  </div>
</div>

<%= link_to "+ Add a new Dose", new_cocktail_dose_path(@cocktail) %>
<br>
<%= link_to "Back to cocktail list", cocktails_path %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<h1>Add a dose to cocktail: <%= @cocktail.name %></h1>


<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>